const ProjectList = [
  `Project A`,
  `Project B`,
  `Project C`,
  `Project A`,
  `Project B`,
  `Project C`,
  `Project A`,
  `Project B`,
  `Project C`,
  `Project A`,
  `Project B`,
  `Project C`,
  `Project A`,
  `Project B`,
  `Project C`,
  `Project A`,
  `Project B`,
  `Project C`,
  `Project A`,
  `Project B`,
  `Project C`,
  `Project A`,
  `Project B`,
]

export default ProjectList
